[package]
name = "libredfish2"
description = "A redfish library.  Useful for querying server hardware"
authors = ["Nathanael G. Reese <nathanaelreese@acm.org>"]
repository = "https://github.com/ngreese/libredfish2"
documentation = "https://docs.rs/libredfish2"
license = "MIT"
version = "0.1.0"
edition = "2024"

[build-dependencies]
#reqwest = {version = "~0.11", features = ["blocking", "json"] }
#serde_json = "~1.0"

[dependencies]
#log = "~0.4"
#reqwest = {version = "~0.11", features = ["blocking", "json"] }
#serde_derive = "~1.0"
#serde = "~1.0"
#serde_json = "~1.0"
